### ISSUE TITLE
time series packages

### ISSUE THREAD

**Issue by topepo** [tidymodels/tidymodels#2]
`tidymodels` has a tagging system so that users can easily load other tidy model packages for a specific domain (e.g text analysis, etc). For example, the user could use:

```r
> tag_update("text analysis")
The following packages are out of date:

● reticulate (1.8 -> 1.9)

Start a clean R session then run:
install.packages("reticulate")

> tag_attach("text analysis")
── Attaching packages ────────────────────────
✔ tidytext 0.1.9     ✔ keras    2.1.6
``` 

These extra packages would not be formal dependencies to `tidymodels`. Also, I'm in the process of defining "how tidy a package needs to be" for inclusion, which I'll document somewhere. 

In the meantime, what tidy time series packages (on CRAN) would @mdancho84, @DavisVaughan, and @robjhyndman suggest for inclusion?

**Comment by mdancho84** [comment]
Thanks for thinking of us Max. We have a Tidy Time Series meeting scheduled for next Monday. We will add this as an agenda item.

**Comment by robjhyndman** [comment]
@mitchelloharawild @earowang

**Comment by topepo** [comment]
I'd like to send this to CRAN this week, so let me know if you 'd like me to add to the existing list.

**Comment by DavisVaughan** [comment]
After a conversation with Rob and his team, we've decided on an exciting collaborative path going forward. That being said, it's not quite ready yet. I see tibbletime and tidyquant are both in there currently. For now, could you remove tibbletime? We can get back to you after we've worked out a few more of the collaboration details. I think it definitely makes sense to include some tidy time series packages here, and they are in active development! But definitely don't let us hold you up for now.

**Comment by mdancho84** [comment]
Would you be OK adding `tidyquant`? It's a financial analysis package that could be useful to people using packages like `tidytext`. Also, it might be good to add `timetk` and `sweep`. `timetk` enables creating forecasts using ML.  `sweep` is the equivalent of `broom` for forecast.

**Comment by mdancho84** [comment]
Awesome! Thanks Max!

**Comment by robjhyndman** [comment]
We should be ready for you to add some more time series tidy packages in the next update.

**Comment by mdancho84** [comment]
Hi Alex,
We have had one tidy time series meeting. We are working on testing out the viability of a major change, but I'd like to keep it private until we are ready to announce. Hopefully, you understand since this is a major collaborative effort and has a lot on the line that needs testing before we are ready to give a green light. 

With that said, we can certainly discuss `sweep` and `broom`. The `sweep` package performs similar `broom` operations for the `forecast` package but also has additional benefits for "tidy" forecasting. One of the main benefits is keeping time stamp information throughout the process of forecasting, which is a challenge when using the `ts` system. 

Here is the compatibility chart, and I'd point you to the [sweep documentation](https://business-science.github.io/sweep/). I spent quite a bit of time on the vignettes, which shows usage and benefits. We can arrange a call or DM to discuss this in more detail.

![image](https://user-images.githubusercontent.com/13734662/43413881-42040474-93ff-11e8-9db9-ba095b20593f.png)

Let me know if you would like to discuss further and I can arrange.

-Matt

**Comment by robjhyndman** [comment]
Just to add to Matt's comments, the `fable` package will (by the end of the year) largely replicate the `forecast` package but using a tidy framework and more consistent interface. We haven't yet decided whether to add broom/sweep-like functionality, or to leave that to a separate package.

The `forecast` package is intended to live on, with maintenance fixes only once `fable` is on CRAN (similar to the relationship between `plyr` and `dplyr`).

**Comment by alexpghayes** [comment]
I think there's some duplicate times series functionality in `broom` that we should really just deprecate in favor of what y'all are doing. @mdancho84 Let's set up a call to discuss details. Moving to email is probably a good idea to avoid cluttering this thread (I'm alexpghayes at gmail).

**Comment by topepo** [comment]
Just added basically all the tidy packages mentioned above.
