### ISSUE TITLE
pragma clang diagnostic pop

### ISSUE THREAD

**Issue by PedroDnT** [tidymodels/tidymodels#30]
Getting this error when trying to install on MacOS Catalina : 

/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/unsupported/Eigen/../../Eigen/src/Core/util/ReenableStupidWarnings.h:10:30: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]

**Comment by juliasilge** [comment]
There were some problems with installing Rcpp on MacOS for a while, and it's possible this was related to that. Do you still have problems installing?

**Comment by DavisVaughan** [comment]
It looks like RcppEigen is being installed from source here. You generally shouldn't have to do that since CRAN builds the binaries for you. It looks like the MacOS binaries for RcppEigen are built for the latest version of the package, so this shouldn't be an issue anymore https://cran.r-project.org/web/packages/RcppEigen/index.html
