### ISSUE TITLE
Decision tree problem with factor conversion

### ISSUE THREAD

**Issue by maksymiuks** [tidymodels/tidymodels#41]
Hi,

I'm afraid I was beaten with a simple classification decision tree use case and I kindly ask for help.

I want to perform classification task on `titanic_imputed` dataset from `DALEX` package. Thing is, target variable which is `survived` is numeric in this dataset, therefore in order to conduct classification I have to convert it into a factor. I want to use a recipe for that purpose. Unfortunately, I met with severe problems. 

First try:

```
library("DALEXtra")
library("tidymodels")
library("recipes")
rec <- recipe(survived ~ ., data = titanic_imputed) %>%
       step_mutate(survived = as.factor(survived)) %>%
       prep()
model <- decision_tree(tree_depth = 25) %>%
         set_engine("rpart") %>%
         set_mode("classification")

wflow <- workflow() %>%
         add_recipe(rec) %>%
         add_model(model)


model_fitted <- wflow %>%
                fit(data = titanic_imputed)

predict(model_fitted, titanic_imputed)
```

Unfortunately predict function returns an error (may be slightly different, I translated it from my locale)

```
ERROR: Problem with `mutate()` input `survived`.
x object 'survived' wasn't found
i Input `survived` is `as.factor(survived)`.
```

and when I try to look on the data frame after transformation 

```
prep(rec, titanic_imputed) %>% bake(titanic_imputed)

 # A tibble: 2,207 x 8
   gender   age class embarked     fare sibsp parch survived
   <fct>  <dbl> <fct> <fct>       <dbl> <dbl> <dbl> <fct>   
 1 male      42 3rd   Southampton  7.11     0     0 0       
 2 male      13 3rd   Southampton 20.0      0     2 0       
 3 male      16 3rd   Southampton 20.0      1     1 0       
 4 female    39 3rd   Southampton 20.0      1     1 1       
 5 female    16 3rd   Southampton  7.13     0     0 1       
 6 male      25 3rd   Southampton  7.13     0     0 1       
 7 male      30 2nd   Cherbourg   24        1     0 0       
 8 female    28 2nd   Cherbourg   24        1     0 1       
 9 male      27 3rd   Cherbourg   18.2      0     0 1       
10 male      20 3rd   Southampton  7.18     0     0 1       
# ... with 2,197 more rows
Warning:
 There was 1 column that was a factor when the recipe was prepped:
 'survived'.
 This may cause errors when processing new data. 
```

Second try: 

```
library("DALEXtra")
library("tidymodels")
library("recipes")
rec <- recipe(survived ~ ., data = titanic_imputed) %>%
       step_num2factor(survived, transform = function(x) x + 1, levels = c("0", "1")) %>%
       prep()
model <- decision_tree(tree_depth = 25) %>%
         set_engine("rpart") %>%
         set_mode("classification")

wflow <- workflow() %>%
         add_recipe(rec) %>%
         add_model(model)


model_fitted <- wflow %>%
                fit(data = titanic_imputed)


ERROR: Column names `survived`, `survived`, `..levels`, `..levels`, `survived`, and 2200 more must not be duplicated.
```

And the output of the bake function is the same as in the first try.

Where is the problem I make? How should the recipe look like for classification tasks if original data contain a numerical target?

Best Regards
Szymon Maksymiuk

**Comment by juliasilge** [comment]
The first thing is that you cannot use a prepped recipe in a workflow; the worfklows package takes care of `prep()`/`bake()` for you, especially in the case of resampling. You only need to pass in a bare recipe. Notice [in this article how the recipe](https://www.tidymodels.org/start/recipes/#features) does **not** use `prep()` before it is added via `add_recipe()`. We need to make the error message better for when the user adds a prepped recipe to a workflow; an issue for this is open in tidymodels/workflows#69.

The second thing is that we wouldn't recommend using a recipe at all in this case because you are **transforming the outcome variable**. This can become a problem when you have _new data_, such as when you are predicting on test data or in resampling. When the recipe goes to make its transformations on new data but it is time for prediction, there is nothing there! You can use `skip = TRUE` if you like, or since this is not really a statistical transformation that needs to be learned from the training data, you can do it ahead of time:

``` r
library(DALEXtra)
#> Loading required package: DALEX
#> Welcome to DALEX (version: 1.3.1.1).
#> Find examples and detailed introduction at: https://pbiecek.github.io/ema/
#> Additional features will be available after installation of: ggpubr.
#> Use 'install_dependencies()' to get all suggested dependencies
library(tidymodels)

titanic_imputed <- titanic_imputed %>%
  mutate(survived = factor(survived))

tree_spec <- decision_tree(tree_depth = 25) %>%
  set_engine("rpart") %>%
  set_mode("classification")

titanic_wf <- workflow() %>%
  add_model(tree_spec) %>%
  add_formula(survived ~ .)

titanic_fitted <- titanic_wf %>%
  fit(data = titanic_imputed)

predict(titanic_fitted, titanic_imputed)
#> # A tibble: 2,207 x 1
#>    .pred_class
#>    <fct>      
#>  1 0          
#>  2 0          
#>  3 0          
#>  4 0          
#>  5 1          
#>  6 0          
#>  7 0          
#>  8 1          
#>  9 0          
#> 10 0          
#> # … with 2,197 more rows
```

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by maksymiuks** [comment]
I appreciate Your prompt answer, thank You.

Thank You as well for pointing me out the mistake caused by the usage of `prep()` function. I had to accidentally skip that part of the article.

About transformation, to be honest I thought transforming target variable fits workflow ideas as well. I didn't think about issues with new data, thank You for pointing it out, the reasoning is quite valid. However, I'd like to suggest making a more informative warning if someone tries to transform the target variable just like I did. Shouldn't be hard as formulas in the recipe do not allow inline function, so the name of the target is pretty easy to acquire. Right now I thought, I'm just bad at usage workflows, didn't have even glimpse of thought that transforming a target may be a nono.

**Comment by juliasilge** [comment]
We definitely are working on our documentation and training around transforming the outcome, because of the complexity involved. We wouldn't recommend using a recipe in the case you showed here because it is such a simple transformation that can be implemented in data cleaning. There are other cases where you may need to use a recipe, and in that case you would use `skip = TRUE`:

``` r
library(DALEXtra)
#> Loading required package: DALEX
#> Welcome to DALEX (version: 1.3.1.1).
#> Find examples and detailed introduction at: https://pbiecek.github.io/ema/
#> Additional features will be available after installation of: ggpubr.
#> Use 'install_dependencies()' to get all suggested dependencies
library(tidymodels)

titanic_rec <- recipe(survived ~ ., data = titanic_imputed) %>%
  step_mutate(survived = factor(survived), skip = TRUE) 

tree_spec <- decision_tree(tree_depth = 25) %>%
  set_engine("rpart") %>%
  set_mode("classification")

titanic_wf <- workflow() %>%
  add_model(tree_spec) %>%
  add_recipe(titanic_rec)

titanic_fitted <- titanic_wf %>%
  fit(data = titanic_imputed)

predict(titanic_fitted, titanic_imputed)
#> # A tibble: 2,207 x 1
#>    .pred_class
#>    <fct>      
#>  1 0          
#>  2 0          
#>  3 0          
#>  4 0          
#>  5 1          
#>  6 0          
#>  7 0          
#>  8 1          
#>  9 0          
#> 10 0          
#> # … with 2,197 more rows
```

<sup>Created on 2020-08-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by maksymiuks** [comment]
I totally understand Your point. Thank You for the assist.
