### ISSUE TITLE
Excel Solver for tidymodels

### ISSUE THREAD

**Issue by agronomofiorentini** [tidymodels/tidymodels#70]
First of all thanks for the amazing package that you have develop.

I created a model with tidymodels that aims to estimate the yield of durum wheat from a set of covariates, among which I have the amount of fertilizer provided to the crop.

The model performs very well, and now I would like to take it to another level, that is, starting from the cost of fertilizer and the selling price of durum wheat, you can ask the model to maximize profit.

Like creating a function that acts like the solver tool in excel?

That is, a function that tries all possible combinations of the amount of fertilizer in order to maximize profit, while making all other covariates remain the same.

For profit I mean yield * sale price (fixed) - quantity of fertilizer * price of fertilizer (fixed).

I hope I have explained myself well, if you need further explanation I will be happy to give it.

**Comment by agronomofiorentini** [comment]
Sorry for the significant delay in responding.

I will try to better explain my need/question.

I have trained a model with several covariates among which is the amount of nitrogen supplied to the crop.

This model aims to predict the yield of the crop.

Now after training the model, I would like to determine the amount of nitrogen that maximizes the yield of the crop knowing the cost of nitrogen and the selling price of the crop.

All this to create a decision support system that can support the farmer in his choices and reduce the environmental impact.

I tried using optim, but couldn't quite figure out how to integrate it with tidymodels. Could you give me an example that I can follow in order to achieve my goal.

I hope I explained myself well this time 🙂

**Comment by juliasilge** [comment]
The base R function `optim()` function doesn't specifically integrate with tidymodels, but if you have a function that you can call, I would expect that you can optimize it. However, it sounds like maybe a partial dependence profile might be what you are looking for? You can read [more about that here](https://www.tmwr.org/explain.html#building-global-explanations-from-local-explanations), and I recommend checking out the rest of that chapter.

For questions like these, that are not about a bug in a package but instead about how to approach a modeling/ML question, we recommend that you:

- create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) showing the main elements of your analysis. The goal of a reprex is to make it easier for people to understand what you are doing so that they can offer advice or ideas. If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page.
- post on [RStudio Community](https://rstd.io/tidymodels-community), under the tag I have linked there. GitHub is great for reporting bugs and fixing code, but RStudio Community is a welcoming space that is well-suited for questions and discussion.

**Comment by agronomofiorentini** [comment]
@juliasilge Thanks for the references i will check it out.

In the future i will use the RStudio community.

From my side the issue is solved.

Thanks Again

**Comment by juliasilge** [comment]
Sounds great! Good luck with your analysis 🙌
