### ISSUE TITLE
Please clarify what belongs in `tidymodels_prefer()`

### ISSUE THREAD

**Issue by RaymondBalise** [tidymodels/tidymodels#72]
## Feature

Can you please clarify the design/plan/guidelines for what belongs in `tidymodels_prefer()` vs additional `conflicted_prefer()` calls?  Currently {yardstick} is preferred for `precision()` and `recall()` but not `spec()` which conflicts with {readr}.

**Comment by juliasilge** [comment]
Like it says in the docs, the intent is:

> to handle common conflicts with tidymodels and other packages.

We don't have an explicit set of guidelines and are using reports of common problems to decide what to include.

I have occasionally run into the issues with `readr::spec()` so that would be a good addition IMO. Thoughts @topepo?

**Comment by EmilHvitfeldt** [comment]
It would also be helpful to show (at least in the documentation) what function we are trying to conflict over. I'm assuming {yardstick} is preferred for `precision()` and `recall()` because they are also exported from {caret}, but I'm not confident.

**Comment by topepo** [comment]
@RaymondBalise It is intended to be optional and gentle.  Echoing @juliasilge's point above, "common" has been loosely defined to be "things that consistently get on our nerves". 

Recommendations would be great. I'd like them to be focused on tidyverse and tidymodels functions (e.g. not `caret::train()` over `RSNNS::train()` etc.)

@EmilHvitfeldt We've specified `conflict_prefer()` to prefer a "winner" and don't specify "losers". I'd leave it at that since we can't predict what other packages will use those function names.

**Comment by RaymondBalise** [comment]
@topepo Cool. I officially suggest that `spec()` be added because it which conflicts with {readr}.

**Comment by juliasilge** [comment]
I think we are all on the same page about that @RaymondBalise. 👍  If you would like to submit a PR adding `spec()` like you mentioned before, that would be fantastic.

**Comment by RaymondBalise** [comment]
Cool. Will do.
