### ISSUE TITLE
Is there a list of methods that supports GPU usage? Documentation on this?

### ISSUE THREAD

**Issue by exsell-jc** [tidymodels/tidymodels#86]
Sorry this isn't exactly an FR. I was led here after: https://community.rstudio.com/t/tidymodels-processing-through-cpu-vs-gpu/132467/4

Which resampling methods, modelling methods, recipe steps, etc. are available for GPU use? Is there such a list?

There doesn't seem to be much buzz around this topic, so I'm asking here also.

**Comment by juliasilge** [comment]
I believe tidymodels packages will correctly call (from R) any special compiled code that is set up for GPU use, but we don't currently lay out which models or feature engineering steps can do that; currently this requires the _user_ to know more about how, say, they can set up keras or xgboost for GPU use. 

We definitely agree that there isn't much interest on this topic for now from our users, which I attribute to the fact that most of the models that get the most use in practical applications by our users (trees and boosted trees, Bayesian models, linear/logistic, SVMs) don't benefit that much from GPUs at the current time. Also, I don't believe any binaries from CRAN have GPU support. We probably won't prioritize this in documentation for the time being because of this.
